version: '3'
services:
  amazon_product:
    build:
      context: ./amazon_product
      dockerfile: Dockerfile
    volumes:
      - ./amazon_product:/amazon_product
      - ./log:/log
    container_name: cidp_amazon_product
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  twitter_user:
    build:
      context: ./twitter_user
      dockerfile: Dockerfile
    volumes:
      - ./twitter_user:/twitter_user
      - ./log:/log
      - C:/Users/Haerin/databases/tweet_info.db:/twitter_user/tweet_info.db
    container_name: cidp_twitter_user
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    