name: Data Collection Workflow

on:
  push:
    branches: [ feat/collect_amazon_twitter ]
  pull_request:
    branches: [ feat/collect_amazon_twitter ]

defaults:
  run:
    shell: bash

jobs:

  data_collection:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run DB initialization script
      run: |
        cd src
        python ./db_init.py

    - name: Upload db log file
      uses: actions/upload-artifact@v2
      with:
        name: db log 
        path: ./log/db_init.log
        
    - name: Download db log file
      uses: actions/download-artifact@v2
      with:
        name: db log 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Amazon data collection
      run: |
        cd src/amazon_product
        python ./collect_executor.py

    - name: Upload Amazon log file
      uses: actions/upload-artifact@v2
      with:
        name: amazon-log
        path: ./log/amazon_product.log
        
    - name: Download Amazon log file
      uses: actions/download-artifact@v2
      with:
        name: amazon-log
        
    - name: Run Twitter data collection
      run: |
        cd src/twitter_user  
        python ./collect_executor.py

    - name: Upload Twitter log file
      uses: actions/upload-artifact@v2
      with:
        name: twitter-log
        path: ./log/twitter.log
        
    - name: Download Twitter log file
      uses: actions/download-artifact@v2
      with:
        name: twitter-log

    - name: Upload sql file
      uses: actions/upload-artifact@v2
      with:
        name: sql
        path: ./tweet_info.db
        
    - name: Download sql file
      uses: actions/download-artifact@v2
      with:
        name: sql
